name: Scrape Airbnb Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 7/24 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrapeAirbnb
          git config user.name airbnb-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Airbnb database"
          git push origin main
