name: Scrape Uniplace Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 6/48 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape
          git config user.email "noreply@example.com"
          git config user.name uniplace-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Uniplace database"
          git push origin main
