name: Scrape SuperCasa Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '1 6/3 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrapeSupercasa
          git config user.name supercasa-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Supercasa database"
          git push origin main
